# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: cypress-deployment
# spec:
#   replicas: 3  # You can adjust the number of replicas as needed
#   selector:
#     matchLabels:
#       app: cypress
#   template:
#     metadata:
#       labels:
#         app: cypress
#     spec:
#       containers:
#         - name: cypress-container
#           image: my-cypress-image:1.1.0  # Replace with your Docker image name and tag
#           ports:
#             - containerPort: 8085  # Adjust the port as needed


apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-cypress-app
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: my-cypress-app
  template:
    metadata:
      labels:
        app: my-cypress-app
    spec:
      containers:
      - name: my-cypress-container
        image: vvishali21/my-cypress-image:1.1.0  # Use the image name and tag from your Jenkins pipeline
        ports:
        - containerPort: 3000  # Adjust the port as needed
---
apiVersion: v1
kind: Service
metadata:
  name: my-cypress-service
spec:
  selector:
    app: my-cypress-app 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000  # External port you want to expose
    targetPort: 3000  # Container port

