apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-cypress-app
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: my-cypress-app
  template:
    metadata:
      labels:
        app: my-cypress-app
    spec:
      containers:
      - name: my-cypress-container
        image: vvishali21/my-cypress-image:1.1.0  # Use the image name and tag from your Jenkins pipeline
        ports:
        - containerPort: 80  # Adjust the port as needed
