version: "3"
services:
  # this container will run Cypress test using built-in Electron browser
  e2e-electron:
    image: "cyp-dock-mocha-report"
    command: "test"
    volumes:
      - ./reports/video:/reports/video
      - ./reports/mochawesome:/reports/mochawesome

  # this container will run Cypress test using Chrome browser
  e2e-chrome:
    image: "cyp-dock-mocha-report"
    command: "chrome:test"
    volumes:
      - ./reports/video:/reports/video
      - ./reports/mochawesome:/reports/mochawesome

  # this container will run Cypress test using Firefox browser
  # note that both Chrome and Firefox browsers were pre-installed in the Docker image
  e2e-firefox:
    image: "cyp-dock-mocha-report"
    command: "firefox:test"
    volumes:
      - ./reports/video:/reports/video
      - ./reports/mochawesome:/reports/mochawesome